package nl.qsight.common;

public class Constants {

    public static String INPUT_MARKER = "<INPUT>";
    public static String OUTPUT_MARKER = "<OUTPUT>";
    public static String TIMESTAMP = "timestamp";
    public static String ORIGINAL_STRING = "original_string";
    public static String AUTOGENERATED_LINK = "_AUTOLINK_";

}
